packages:
  - "tests/fixtures/*"
  - "." # This is needed for changesets to detect the root package

allowBuilds:
  dprint: true

blockExoticSubdeps: true
dedupePeers: true
dedupePeerDependents: true
minimumReleaseAge: 10080

overrides:
  rolldown: ^1.0.0

shellEmulator: true
trustPolicy: no-downgrade
